Feature/project service
bepoland-academy/projects-service pull request #1
Opened 2019-03-13 12:42 UTC by wkrzyzanowski

2019-03-13 13:01 UTC, lukaszfranczuk requested changes

2019-03-13 13:01 UTC, lukaszfranczuk commented on pom.xml
> +            <!--</plugin>-->
please don't commit commented code - if it is not needed remove it

2019-03-13 13:01 UTC, lukaszfranczuk commented on src/main/java/pl/betse/beontime/projectservice/controller/ClientController.java
> +    public ResponseEntity<List<ClientBo>> ListOfAllClients() {
we should not return BO objects to the clients

2019-03-13 13:01 UTC, lukaszfranczuk commented on src/main/java/pl/betse/beontime/projectservice/controller/ClientController.java
> +    public ResponseEntity<ClientBo> updateClient(@PathVariable("guid") String guid, @RequestBody ClientBody clientBody) {
this method doesn't return body, so it should be just ``ResponseEntity`` - without type

2019-03-13 13:01 UTC, lukaszfranczuk commented on src/main/java/pl/betse/beontime/projectservice/controller/ClientController.java
> +    @DeleteMapping("/{guid}")
this method doesn't return body, so it should be just ``ResponseEntity`` - without type

2019-03-13 13:01 UTC, lukaszfranczuk commented on src/main/java/pl/betse/beontime/projectservice/exception/ProjectAlreadyExistException.java
> +@NoArgsConstructor
``@NoArgsConstructor`` is redundant  - it is a default constructor in Java

2019-03-13 13:01 UTC, lukaszfranczuk commented on src/main/java/pl/betse/beontime/projectservice/exception/ProjectNotFoundException.java
> +@NoArgsConstructor
``@NoArgsConstructor``is redundant - it is a default constructor in Java

2019-03-14 15:11 UTC, miles87 submitted a review, later dismissed

2019-03-14 15:54 UTC, lukaszfranczuk requested changes

2019-03-14 15:54 UTC, lukaszfranczuk commented on src/main/java/pl/betse/beontime/projectservice/exception/ClientAlreadyExistException.java
> +@NoArgsConstructor
``@NoArgsConstructor`` is redundant  - this is default constructor in Java

2019-03-14 15:54 UTC, lukaszfranczuk commented on src/main/java/pl/betse/beontime/projectservice/exception/ClientNotFoundException.java
> +@NoArgsConstructor
``@NoArgsConstructor`` is redundant  - this is default constructor in Java

2019-03-14 15:54 UTC, lukaszfranczuk commented on src/main/java/pl/betse/beontime/projectservice/mapper/ProjectMapper.java
> +    )
please use formatter before you push changes to the repository

2019-03-14 15:54 UTC, lukaszfranczuk commented on src/main/java/pl/betse/beontime/projectservice/service/ProjectService.java
> +        ClientEntity clientEntity = clientRepository.findByGuid(projectBo.getClientBo().getClientId()).orElseThrow(ClientNotFoundException::new);
please format it properly

2019-03-14 15:54 UTC, lukaszfranczuk commented on src/main/java/pl/betse/beontime/projectservice/service/ProjectService.java
> +        }
this check should be done in cotroller - all input data should be validated there

2019-03-14 16:44 UTC, miles87 commented on src/main/java/pl/betse/beontime/projectservice/controller/ClientController.java
> +    public ResponseEntity<List<ClientBo>> ListOfAllClients() {
resolved

2019-03-14 16:56 UTC, lukaszfranczuk approved these changes

2019-03-15 07:38 UTC, merged